package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// artifactsRepo chdirs into a temp dir with the delivery sources for feature f.
func artifactsRepo(t *testing.T, f string, withChangelog bool) {
	t.Helper()
	dir := t.TempDir()
	write := func(rel, body string) {
		p := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("docs/features/"+f+".md", "## Problem\n\nbig problem\n\n## Who / Why\n\nfor users\n")
	write("docs/plans/"+f+".md", "## Proposed Architecture\n\narch text\n")
	write(".workflow/"+f+"-gatekeeper.md", "### Gatekeeper Report\n**Status:** SAFE\n")
	write(".workflow/"+f+"-changelog.md", "- feat: ship "+f+"\n")
	write("specs/"+f+".feature", "Feature: x\n")
	if withChangelog {
		write("CHANGELOG.md", "# Changelog\n\n## [Unreleased]\n\n### Added\n\n### Changed\n\n### Fixed\n")
	}
	wd, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
}

func TestBuildPRBodyWritesComposedFile(t *testing.T) {
	artifactsRepo(t, "alpha", true)
	title, path, err := buildPRBody("alpha")
	if err != nil {
		t.Fatalf("buildPRBody: %v", err)
	}
	if title == "" {
		t.Fatal("buildPRBody must return a non-empty PR title")
	}
	defer os.Remove(path)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	body := string(data)
	for _, want := range []string{"## Summary", "big problem", "## Gate status", "SAFE", "specs/alpha.feature", "Generated by Centinela from alpha"} {
		if !strings.Contains(body, want) {
			t.Fatalf("PR body missing %q:\n%s", want, body)
		}
	}
}

func TestWriteChangelogIdempotent(t *testing.T) {
	artifactsRepo(t, "alpha", true)
	changed, err := writeChangelog("alpha")
	if err != nil || !changed {
		t.Fatalf("first write should change: changed=%v err=%v", changed, err)
	}
	changed2, err := writeChangelog("alpha")
	if err != nil || changed2 {
		t.Fatalf("second write must be a no-op: changed=%v err=%v", changed2, err)
	}
	data, _ := os.ReadFile(changelogPath)
	if n := strings.Count(string(data), "- feat: ship alpha"); n != 1 {
		t.Fatalf("expected exactly one line, got %d:\n%s", n, data)
	}
}

func TestWriteChangelogMissingFileNoOp(t *testing.T) {
	artifactsRepo(t, "alpha", false) // no CHANGELOG.md
	changed, err := writeChangelog("alpha")
	if err != nil || changed {
		t.Fatalf("missing CHANGELOG should be a no-op: changed=%v err=%v", changed, err)
	}
}
