package acceptance_test

import (
	"path/filepath"
	"testing"
)

// Acceptance: specs/docstring-gate.feature
//
// Skip is a first-class outcome: an empty changed-file scope, a scope with
// no Go files, a scope containing only test/generated files, and an
// unresolvable merge base must all report Skip — never a confident Pass and
// never a Fail for a scan that opened nothing.

// Scenario: An empty changed-file scope reports Skip, not Pass
func TestDG_EmptyScopeSkips(t *testing.T) {
	bin := buildCentinelaBinary(t)
	dir := setupDocstringRepo(t, "fail")
	out := runValidate(t, bin, dir, []string{"--changed"})
	mustContain(t, out, "docstring-gate  No changed files")
	mustNotContain(t, out, "docstring-gate  All")
}

// Scenario: A changed-file scope with no Go files reports Skip
func TestDG_NoGoFilesInScopeSkips(t *testing.T) {
	bin := buildCentinelaBinary(t)
	dir := setupDocstringRepo(t, "fail")
	mustWrite(t, filepath.Join(dir, "README.md"), "# hello\n")
	commit(t, dir, "add readme")
	out := runValidate(t, bin, dir, []string{"--changed"})
	mustContain(t, out, "docstring-gate  No Go files in scope under roots [src]")
}

// Scenario: Test files and generated files are never reported
func TestDG_TestAndGeneratedFilesSkip(t *testing.T) {
	bin := buildCentinelaBinary(t)
	dir := setupDocstringRepo(t, "fail")
	writeDocFile(t, dir, "a_test.go", "package a\n\nfunc Exported() {}\n")
	writeDocFile(t, dir, "b.go", "// Code generated by x. DO NOT EDIT.\n\npackage a\n\nfunc G() {}\n")
	commit(t, dir, "add test and generated files")
	out := runValidate(t, bin, dir, []string{"--changed"})
	mustContain(t, out, "docstring-gate  No Go files inspected — every file in scope was generated")
}

// Scenario: An unresolvable changed-file scope reports Skip, not Pass and not Fail
func TestDG_UnresolvableScopeSkips(t *testing.T) {
	bin := buildCentinelaBinary(t)
	dir := t.TempDir()
	runGit(t, dir, "init", "-q", "-b", "other")
	runGit(t, dir, "config", "user.email", "test@centinela.dev")
	runGit(t, dir, "config", "user.name", "Test")
	mustWrite(t, filepath.Join(dir, "centinela.toml"), docstringToml("fail"))
	mustWrite(t, filepath.Join(dir, "src", "legacy.go"), "package a\n\nfunc Legacy() {}\n")
	runGit(t, dir, "add", ".")
	runGit(t, dir, "commit", "-q", "-m", "init")
	out := runValidate(t, bin, dir, []string{"--changed"})
	mustContain(t, out, "docstring-gate")
	mustContain(t, out, "unresolved")
	mustContain(t, out, `diff base "main" not found`)
	mustNotContain(t, out, "docstring-gate  All")
}
