package brownmap

import (
	"github.com/samuelnp/centinela/internal/analyze"
	"github.com/samuelnp/centinela/internal/reconstruct"
	"github.com/samuelnp/centinela/internal/roadmap"
)

// introNote is the top-of-file blockquote rendered into the draft roadmap so a
// reviewer knows the file is a generated draft, not a curated roadmap.
const introNote = "Draft roadmap generated by `centinela roadmap brownfield`. " +
	"The Baseline phase records already-built capability and is exempt from " +
	"status, validate coverage, and readiness; review and edit before adopting."

// Generate regenerates the in-process Reconstruction from inv, then assembles a
// draft Roadmap: a Baseline phase (one feature per reconstructed target) followed
// by gap phase(s) seeded from the TODO-bearing targets and the user-stated goals.
// It performs no I/O and is byte-stable for a given (inv, goals) because every
// input is sorted/explicit (reconstruct's sorted Targets, the caller's goal
// order) and assembly is pure struct/string work with no map iteration.
func (ruleBrownfielder) Generate(inv analyze.Inventory, goals []string) Plan {
	r := reconstruct.NewReconstructor().Reconstruct(inv)
	baseline := baselinePhase(r.Targets)
	gaps := gapPhases(r.TodoTargets(), goals)

	phases := []roadmap.Phase{baseline}
	gapCount := 0
	for _, g := range gaps {
		phases = append(phases, g)
		gapCount += len(g.Features)
	}
	return Plan{
		Roadmap:       roadmap.Roadmap{Intro: introNote, Phases: phases},
		BaselineCount: len(baseline.Features),
		GapCount:      gapCount,
		DraftPath:     DefaultDraftPath,
	}
}
