package delivery

import (
	"strings"
	"testing"
)

func TestComposePRBodyFull(t *testing.T) {
	e := Evidence{
		Feature:          "alpha",
		Brief:            secBrief,
		Plan:             "## Proposed Architecture\n\narch text\n",
		GatekeeperReport: "**Status:** SAFE",
		SpecPath:         "specs/alpha.feature",
	}
	body := ComposePRBody(e)
	// All four sections plus footer, in order.
	idxSummary := strings.Index(body, "## Summary")
	idxWhat := strings.Index(body, "## What changed / Why")
	idxAcc := strings.Index(body, "## Acceptance")
	idxGate := strings.Index(body, "## Gate status")
	idxFoot := strings.Index(body, "Generated by Centinela")
	for _, i := range []int{idxSummary, idxWhat, idxAcc, idxGate, idxFoot} {
		if i < 0 {
			t.Fatalf("missing section in body:\n%s", body)
		}
	}
	if !(idxSummary < idxWhat && idxWhat < idxAcc && idxAcc < idxGate && idxGate < idxFoot) {
		t.Fatalf("sections out of order:\n%s", body)
	}
	if !strings.HasSuffix(body, "\n") {
		t.Fatal("body should end with newline")
	}
}

func TestComposePRBodyOnlyProvenance(t *testing.T) {
	body := ComposePRBody(Evidence{Feature: "alpha"})
	if strings.Contains(body, "## Summary") || strings.Contains(body, "## Gate status") {
		t.Fatalf("no sections should appear when sources empty:\n%s", body)
	}
	if !strings.Contains(body, "Generated by Centinela from alpha") {
		t.Fatalf("provenance must always be present:\n%s", body)
	}
}
