package delivery

import (
	"fmt"
	"strings"
)

const provenanceLine = "_Generated by Centinela from %s delivery evidence._"

// summarySection renders the PR summary from the brief's `## Problem` section,
// falling back to the plan's `## Problem & Goal`. Returns "" when neither
// source has the heading.
func summarySection(e Evidence) string {
	body := ExtractSection(e.Brief, "Problem")
	if body == "" {
		body = ExtractSection(e.Plan, "Problem & Goal")
	}
	if body == "" {
		return ""
	}
	return "## Summary\n\n" + FirstParagraph(body)
}

// whatWhySection renders "What changed / Why" from the brief's `## Who / Why`,
// folding in the plan summary when present. Each absent half is dropped.
func whatWhySection(e Evidence) string {
	parts := []string{}
	if w := ExtractSection(e.Brief, "Who / Why"); w != "" {
		parts = append(parts, FirstParagraph(w))
	}
	if p := ExtractSection(e.Plan, "Proposed Architecture"); p != "" {
		parts = append(parts, FirstParagraph(p))
	}
	if len(parts) == 0 {
		return ""
	}
	return "## What changed / Why\n\n" + strings.Join(parts, "\n\n")
}

// acceptanceSection renders the acceptance reference from the brief's
// `## Acceptance Summary` plus a literal spec pointer. Omitted entirely when
// neither the heading nor a spec path is available.
func acceptanceSection(e Evidence) string {
	body := ExtractSection(e.Brief, "Acceptance Summary")
	pointer := ""
	if strings.TrimSpace(e.SpecPath) != "" {
		pointer = "See acceptance spec: `" + strings.TrimSpace(e.SpecPath) + "`."
	}
	if body == "" && pointer == "" {
		return ""
	}
	segs := []string{}
	if body != "" {
		segs = append(segs, body)
	}
	if pointer != "" {
		segs = append(segs, pointer)
	}
	return "## Acceptance\n\n" + strings.Join(segs, "\n\n")
}

// gateStatusSection renders the gate-status line from the gatekeeper verdict
// and the verification tally. It OMITS any datum it cannot source and returns
// "" when neither is available — it never prints a passing gate it cannot back.
func gateStatusSection(e Evidence) string {
	lines := []string{}
	if v := gatekeeperVerdict(e.GatekeeperReport); v != "" {
		lines = append(lines, "Gatekeeper verdict: "+v)
	}
	if e.Verification != nil {
		pass, fail, skip, warn := e.Verification.Tally()
		lines = append(lines, fmt.Sprintf(
			"Claim verification: %d pass, %d fail, %d skip, %d warn", pass, fail, skip, warn))
	}
	if len(lines) == 0 {
		return ""
	}
	return "## Gate status\n\n" + strings.Join(lines, "\n")
}

// provenanceFooter is the one guaranteed section: constant text only.
func provenanceFooter(e Evidence) string {
	return fmt.Sprintf(provenanceLine, e.Feature)
}
