package gates

import (
	"strings"
	"testing"

	"github.com/samuelnp/centinela/internal/gitdiff"
)

func TestCheckDocstring_EmptyScopeSkipsRatherThanPasses(t *testing.T) {
	inDir(t)
	r := checkDocstring(docstringCfg("fail"), gitdiff.NewSet(nil))
	if r.Status != Skip {
		t.Fatalf("status = %v, want Skip", r.Status)
	}
	if !strings.Contains(r.Message, "nothing inspected") {
		t.Fatalf("message = %q", r.Message)
	}
}

func TestCheckDocstring_ScopeWithNoGoFilesSkips(t *testing.T) {
	inDir(t)
	r := checkDocstring(docstringCfg("fail"), gitdiff.NewSet([]string{"README.md"}))
	if r.Status != Skip || !strings.Contains(r.Message, "No Go files in scope") {
		t.Fatalf("status=%v message=%q", r.Status, r.Message)
	}
}

func TestCheckDocstring_TestAndGeneratedFilesOnlySkipWithNoDetails(t *testing.T) {
	inDir(t)
	tf := fixture(t, "a_test.go", "package a\n\nfunc Exported() {}\n")
	gf := fixture(t, "b.go", "// Code generated by x. DO NOT EDIT.\n\npackage a\n\nfunc G() {}\n")
	r := checkDocstring(docstringCfg("fail"), gitdiff.NewSet([]string{tf, gf}))
	if r.Status != Skip {
		t.Fatalf("status = %v (%s)", r.Status, r.Message)
	}
	if len(r.Details) != 0 {
		t.Fatalf("details = %v", r.Details)
	}
}

func TestCheckDocstring_NilFilterRatchetsToTheChangedSetNotAFullScan(t *testing.T) {
	inDir(t)
	fixture(t, "legacy.go", "package a\n\nfunc Legacy() {}\n")
	changed := fixture(t, "new.go", "package a\n\nfunc New() {}\n")
	stubRatchet(t, gitdiff.NewSet([]string{changed}), "")

	r := checkDocstring(docstringCfg("fail"), nil)
	if r.Status != Fail {
		t.Fatalf("status = %v (%s)", r.Status, r.Message)
	}
	if len(r.Details) != 1 || !strings.Contains(r.Details[0], "new.go") {
		t.Fatalf("a full scan leaked in: %v", r.Details)
	}
}

func TestCheckDocstring_UnresolvableScopeSkipsAndNamesTheReason(t *testing.T) {
	inDir(t)
	fixture(t, "legacy.go", "package a\n\nfunc Legacy() {}\n")
	stubRatchet(t, nil, "not a git repository")

	r := checkDocstring(docstringCfg("fail"), nil)
	if r.Status != Skip {
		t.Fatalf("status = %v, want Skip — an unresolvable scope is never a verdict", r.Status)
	}
	if !strings.Contains(r.Message, "not a git repository") {
		t.Fatalf("message = %q", r.Message)
	}
}

func TestDocstringRatchet_DefaultDelegatesToTheSharedResolver(t *testing.T) {
	inDir(t)
	set, degrade := docstringRatchet("main")
	if degrade == "" && set == nil {
		t.Fatal("the default ratchet must return either a set or a degrade reason")
	}
}
