package synthesize

import (
	"fmt"
	"strings"

	"github.com/samuelnp/centinela/internal/analyze"
)

// Draft assembles a complete PROJECT.md draft string from the inventory and the
// inference. It performs no I/O and is byte-stable for a given input. Sections
// it cannot infer (elevator pitch, domain language) are emitted as TODO stubs so
// the draft is honestly incomplete rather than fabricated.
func Draft(inv analyze.Inventory, inf Inference) string {
	p := profiles[inf.Best]
	return strings.Join([]string{
		header(inf),
		renderArchitecture(inf, p),
		renderTechStack(inv),
		renderFolder(inv),
		renderLayerMapping(inv, p),
		renderNaming(inv),
		renderLocales(inv),
		renderGatekeeper(inv, p),
	}, "\n\n") + "\n"
}

// header emits the doc-version marker, a DRAFT banner the user must act on, and
// the inferred-archetype confidence callout with its rationale.
func header(inf Inference) string {
	var b strings.Builder
	b.WriteString("<!-- centinela:doc-version=1 template=PROJECT.md.template -->\n")
	b.WriteString("# <Project Name> — Project Definition\n\n")
	b.WriteString("<!-- DRAFT: generated by `centinela synthesize` from .workflow/analysis.json.\n")
	b.WriteString("     Review every section, fill the TODOs, then rename to PROJECT.md. -->\n\n")
	b.WriteString(fmt.Sprintf("> **Inferred archetype:** %s — confidence **%s**.", inf.Best, inf.Confidence))
	if inf.Ambiguous {
		b.WriteString(" Ambiguous: scores were close — verify the Architecture Choice below.")
	}
	b.WriteString("\n")
	if reasons := inf.Reasons(); len(reasons) > 0 {
		b.WriteString(">\n> Rationale:\n")
		for _, r := range reasons {
			b.WriteString("> - " + r + "\n")
		}
	}
	return strings.TrimRight(b.String(), "\n")
}
