package synthesize

import (
	"strings"
	"testing"

	"github.com/samuelnp/centinela/internal/analyze"
)

func TestDraft_FullNTier(t *testing.T) {
	in := inv("Go", []string{"internal/handler", "internal/service", "internal/repository", "cmd/api"},
		analyze.Manifest{Kind: "go-mod", Path: "go.mod", Framework: "Express", Build: "go build", Test: "go test"})
	in.Locales = []string{"en", "es"}
	out := Draft(in, NewInferer().Infer(in))
	for _, want := range []string{
		"<!-- centinela:doc-version=1", "DRAFT: generated by", "**Archetype:** n-tier",
		"## Layer Mapping", "`internal/handler`", "## Tech Stack", "Express", "`go build`",
		"## Naming Conventions", "_test.go", "## Gatekeeper Paths", "`specs/`", "| `es` |",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("draft missing %q", want)
		}
	}
}

func TestDraft_EmptyEmitsStubs(t *testing.T) {
	out := Draft(inv("", nil), NewInferer().Infer(inv("", nil)))
	for _, want := range []string{
		"**Archetype:** custom", "<!-- TODO", "no packages detected", "| `en` |",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("empty draft missing %q:\n%s", want, out)
		}
	}
	// Re-running is byte-identical.
	if out != Draft(inv("", nil), NewInferer().Infer(inv("", nil))) {
		t.Fatal("draft must be byte-stable")
	}
}

func TestDraft_AmbiguousBannerAndUnknownLangNaming(t *testing.T) {
	in := inv("Cobol", []string{"service", "domain"})
	out := Draft(in, NewInferer().Infer(in))
	if !strings.Contains(out, "Ambiguous") {
		t.Errorf("ambiguous inference should banner: %s", out)
	}
	if !strings.Contains(out, "| Identifiers | <!-- TODO: confirm -->") {
		t.Errorf("unknown language naming should TODO")
	}
}

func TestMatchPaths_NoHitTODO(t *testing.T) {
	if got := matchPaths([]string{"a", "b"}, "zzz"); !strings.HasPrefix(got, "<!--") {
		t.Fatalf("no match should TODO, got %q", got)
	}
}
