package docstring

import (
	"strings"
	"testing"
)

func TestScan_UndocumentedExportedFuncIsAViolation(t *testing.T) {
	p := writeGo(t, "a.go", "package a\n\nfunc Exported() {}\n")
	rep := scan(t, anyRoot(), p)
	if len(rep.Violations) != 1 {
		t.Fatalf("want 1 violation, got %v", names(rep))
	}
	v := rep.Violations[0]
	if v.Kind != "func" || v.Name != "Exported" || v.Line != 3 {
		t.Fatalf("unexpected violation %+v", v)
	}
	if rep.OK() {
		t.Fatal("report with a violation must not be OK")
	}
	if !strings.Contains(v.String(), "func Exported has no doc comment") {
		t.Fatalf("detail line: %s", v.String())
	}
}

func TestScan_DocumentedExportedIdentifiersPass(t *testing.T) {
	src := "package a\n\n// Exported does a thing.\nfunc Exported() {}\n\n" +
		"// T is a type.\ntype T struct{}\n\n// M is a method.\nfunc (T) M() {}\n"
	rep := scan(t, anyRoot(), writeGo(t, "a.go", src))
	if !rep.OK() {
		t.Fatalf("want OK, got %v", names(rep))
	}
	if rep.Inspected != 3 || rep.Files != 1 {
		t.Fatalf("inspected=%d files=%d", rep.Inspected, rep.Files)
	}
}

func TestScan_UnexportedAndUnexportedReceiversAreIgnored(t *testing.T) {
	src := "package a\n\nfunc hidden() {}\n\ntype t struct{}\n\nfunc (t) M() {}\n" +
		"\nfunc (*t) N() {}\n"
	rep := scan(t, anyRoot(), writeGo(t, "a.go", src))
	if rep.Inspected != 0 || !rep.OK() {
		t.Fatalf("inspected=%d violations=%v", rep.Inspected, names(rep))
	}
}

func TestScan_TestAndGeneratedFilesAreNeverInspected(t *testing.T) {
	test := writeGo(t, "a_test.go", "package a\n\nfunc Exported() {}\n")
	gen := writeGo(t, "b.go", "// Code generated by x. DO NOT EDIT.\n\npackage a\n\nfunc G() {}\n")
	rep := scan(t, anyRoot(), test, gen)
	if rep.Files != 0 || rep.Inspected != 0 || !rep.OK() {
		t.Fatalf("files=%d inspected=%d violations=%v", rep.Files, rep.Inspected, names(rep))
	}
}

func TestScan_MissingFileIsSkippedButUnparseableIsReported(t *testing.T) {
	broken := writeGo(t, "broken.go", "package a\n\nfunc (((\n")
	rep := scan(t, anyRoot(), broken, "does/not/exist.go")
	if len(rep.ParseErrors) != 1 || !strings.HasSuffix(rep.ParseErrors[0].Path, "broken.go") {
		t.Fatalf("parse errors: %+v", rep.ParseErrors)
	}
	if rep.OK() {
		t.Fatal("an unparseable file must not be OK")
	}
	if !strings.Contains(rep.Lines()[0], "unparseable Go file") {
		t.Fatalf("lines: %v", rep.Lines())
	}
}
